Add a currently failing mypy test which reproduces the issue #21907 (python with valid type annotations crashing mypy but not e.g. pyright, pyrefly who pass it)
New test "testGenericTypeWithConstrainedTypeVarShouldNotInterfereWithVarargsArgumentTypeChecking" should fail until #21907 is fixed
with an INTERNAL ERROR caused by a traceback ending with:
```
File "/home/liveuser/mypy/mypy/types_utils.py", line 183, in store_argument_type
 defn.arguments[i].variable.type = arg_type
 ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

When using other type checkers like pyright 1.1.414 and pyrefly 1.3.1, there is no crash (INTERNAL ERROR) and also there are no type errors found for the example used in this test case.